// <auto-generated />
using System;
using Asp.NetCore.BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.NetCore.BookStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.NetCore.BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("BorrowedCopies");

                    b.Property<int>("CopiesLeft");

                    b.Property<int>("CopiesNumber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<float?>("Rate");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "j.d.salinger",
                            BorrowedCopies = 4,
                            CopiesLeft = 2,
                            CopiesNumber = 6,
                            Name = "the catcher in the rye",
                            Rate = 3.1f
                        },
                        new
                        {
                            Id = 2,
                            Author = "harper lee",
                            BorrowedCopies = 1,
                            CopiesLeft = 4,
                            CopiesNumber = 5,
                            Name = "to kill a mockingbird",
                            Rate = 4.2f
                        },
                        new
                        {
                            Id = 3,
                            Author = "jane austen",
                            BorrowedCopies = 2,
                            CopiesLeft = 5,
                            CopiesNumber = 7,
                            Name = "pride and prejudice",
                            Rate = 4.9f
                        },
                        new
                        {
                            Id = 4,
                            Author = "j. k. rowling",
                            BorrowedCopies = 1,
                            CopiesLeft = 3,
                            CopiesNumber = 4,
                            Name = "harry potter and the philosopher's stone",
                            Rate = 4.8f
                        },
                        new
                        {
                            Id = 5,
                            Author = "wiiliam shakespeare",
                            BorrowedCopies = 0,
                            CopiesLeft = 3,
                            CopiesNumber = 3,
                            Name = "hamlet",
                            Rate = 4.6f
                        },
                        new
                        {
                            Id = 6,
                            Author = "wiiliam shakespeare",
                            BorrowedCopies = 0,
                            CopiesLeft = 3,
                            CopiesNumber = 3,
                            Name = "othelo",
                            Rate = 4.4f
                        },
                        new
                        {
                            Id = 7,
                            Author = "john green",
                            BorrowedCopies = 0,
                            CopiesLeft = 5,
                            CopiesNumber = 5,
                            Name = "the fault in our stars",
                            Rate = 3.4f
                        },
                        new
                        {
                            Id = 8,
                            Author = "hilary mantelr",
                            BorrowedCopies = 0,
                            CopiesLeft = 3,
                            CopiesNumber = 3,
                            Name = "wolf hall",
                            Rate = 3.9f
                        },
                        new
                        {
                            Id = 9,
                            Author = "yann martel",
                            BorrowedCopies = 1,
                            CopiesLeft = 3,
                            CopiesNumber = 4,
                            Name = "life of pi",
                            Rate = 4f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
